// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(account_id))]
pub struct Account {
    pub account_id: i32,
    pub email: String,
}

#[derive(Queryable, Debug, Identifiable)]
#[diesel(primary_key(todo_id))]
pub struct Todo {
    pub account_id: Option<i32>,
    pub todo_id: i32,
    pub created_at: NaiveDateTime,
    pub updated_at: Option<NaiveDateTime>,
    pub title: String,
    pub status: String,
}

