// Generated by diesel_ext
use diesel::{Queryable, Insertable};
use serde::{Serialize, Deserialize};
use crate::schema::accounts;

#[derive(Queryable, Debug, Serialize)]
#[diesel(primary_key(account_id))]
pub struct Account {
    pub account_id: i32,
    pub email: String,
}

#[derive(Insertable)]
#[table_name="accounts"]
pub struct NewAccount {
    pub email: String,
}

#[derive(Serialize, Deserialize)]
pub struct CreateAccountParam {
    pub email: String,
}